/* Cliente.cpp - Generated by Visual Multi-Thread Win32 */

// WIN32_LEAN_AND_MEAN macro prevents the Winsock.h from being 
// included by the Windows.h header
#define WIN32_LEAN_AND_MEAN
//#include <windows.h>
// The Winsock2.h header file contains most of the Winsock functions, 
// structures, and definitions. The Ws2tcpip.h header file contains 
// definitions introduced in the WinSock 2 Protocol-Specific
// The Winsock2.h header file internally includes core elements from 
// the Windows.h header file
#include <winsock2.h>
#include <ws2tcpip.h>
#include <stdlib.h>
#include <stdio.h>
#include "AppObjects.h"
#include "my_socket.h"
#include <string>
#include <cstdio>
#include <iostream>

using namespace std;

// Need to link with Ws2_32.lib, Mswsock.lib, and Advapi32.lib
#pragma comment (lib, "Ws2_32.lib")
#pragma comment (lib, "Mswsock.lib")
#pragma comment (lib, "AdvApi32.lib")

DWORD WINAPI thread_Cliente(LPVOID lpParameter);

DWORD WINAPI thread_Cliente(LPVOID lpParameter)
{
	// Create a WSADATA object called wsaData.
	WSADATA wsaData;
	SOCKET ConnectSocket = INVALID_SOCKET;
	// Declare an addrinfo object that contains a sockaddr structure 
	// and initialize these values.
	struct addrinfo *result = NULL,
	                *ptr = NULL,
	                hints;
	
	int iResult;
	int recvbuflen = DEFAULT_BUFLEN;
	message msg1;
	unsigned char mc_ttl=1;     /* time to live (hop count) */
	
	SocketParams *params;
	params = (SocketParams *)lpParameter;
	
	printf("Entre com o mome do Cliente: \n");
	scanf("%s", &msg1.name);
	msg1.nro_msg=1;
	
	// Initialize Winsock  
	// The WSAStartup function is called to initiate use of WS2_32.dll
	// The MAKEWORD(2,2) parameter of WSAStartup makes a request for 
	// version 2.2 of Winsock on the system
	iResult = WSAStartup(MAKEWORD(2,2), &wsaData);
	if (iResult != 0) 
	         {
	          printf("WSAStartup failed with error: %d\n", iResult);
				 return 1;
		        }
	
	ZeroMemory(&hints, sizeof(hints));
	// Internet address family is unspecified so that either an 
	// IPv6 or IPv4 address can be returned. The application requests 
	// the socket type to be a stream socket for the TCP protocol
	hints.ai_family = params->family;
	hints.ai_socktype = params->socktype;
	hints.ai_protocol = params->protocol;
	
	/* Resolve the server address and port */
	// getaddrinfo function request the IP address for the server name and 
	// the TCP port on the server that the client will connect
	iResult = getaddrinfo(params->ip, params->port, &hints, &ptr);
	if ( iResult != 0 ) {
		           printf("getaddrinfo failed with error: %d\n", iResult);
		           WSACleanup();
		           return 1;
	                     	}
	/* Create a SOCKET for connecting to server */
	ClientSocket = socket(ptr->ai_family, ptr->ai_socktype, ptr->ai_protocol);
	if (ClientSocket == INVALID_SOCKET) 
		   {
		   printf("socket failed with error: %ld\n", WSAGetLastError());
		   WSACleanup();
		   return 1;
		     }
			  	
	/* set the TTL (time to live/hop count) for the send */
	if ((setsockopt(ClientSocket, SOL_SOCKET, SO_BROADCAST,
	       (const char *) &mc_ttl, sizeof(mc_ttl))) < 0) {
	    perror("setsockopt() failed");
	    exit(1);
	  } 
	  
	char status='A';
	while(status!='f')
	{
		printf("Enter the Client msg: \n");
		scanf("%s", &msg1.buf); 
		
		iResult = sendto(ClientSocket, (const char *)&msg1, (int)sizeof(msg1), 0, ptr->ai_addr, ptr->ai_addrlen);
		if (iResult == SOCKET_ERROR) {
		printf("send failed with error: %d\n", WSAGetLastError());
		closesocket(ClientSocket);
		WSACleanup();
		return 1;
		}
		
		printf("Sender - Bytes Sent: %ld\n", iResult);
		
		Sleep(10);
		msg1.nro_msg++;
				
		printf("Tecle: f - Para terminar ou c - Para enviar outra mensagem \n");
				
		status='A';
		while ((status!='f') && (status!='c'))
		                {status=getchar();  Sleep(10);}
		
	}
	closesocket(ClientSocket);
	return 0;
}
