/* main.cpp - Generated by Visual Multi-Thread Win32 */

#include "AppObjects.h"
#include "my_socket.h"
#include <stdlib.h>
#include <stdio.h>

extern DWORD WINAPI thread_Cliente(LPVOID lpParameter);
int main(int argc, char *argv[]);

int main(int argc, char *argv[])
{
	SocketParams params;
	
	/* validate number of arguments */
	  if (argc != 2) {
	    printf("Usage: %s <Broadcast IP>\n Broadcast IP address: 255.255.255.255 \n", 
	            argv[0]);
	    exit(1);
	  }
	
	strcpy(params.port, "27015");
	params.ip= argv[1];
	
	params.family = AF_UNSPEC;
	params.socktype = SOCK_DGRAM;
	params.protocol= IPPROTO_UDP;
	
	Cliente = CreateThread(0, 0,(LPTHREAD_START_ROUTINE) thread_Cliente, &params, 0, 0);
	WaitForSingleObject(Cliente, INFINITE);
}
